[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
solc_version = "0.8.24"
evm_version = "paris"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[ffi]
enabled = true
